### ISSUE TITLE
Fun feature: Add a "view a random dataset" option

### ISSUE THREAD

**Issue by KarenJewell** [OpenDataScotland/jkan#24]

**Comment by JackGilmore** [comment]
![image](https://github.com/OpenDataScotland/jkan/assets/46202639/6301e2b9-01e4-475d-ba24-0a428c87c4b1)
@KarenJewell Do you reckon we still need this now that we have the 5 random datasets listing on the front page?

**Comment by JackGilmore** [comment]
Closing as no longer needed. We expose 5 random datasets on the front page that change on page refresh.
